version: '3'
services:

  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      #- POSTGRES_HOST_AUTH_METHOD=trust
      #- POSTGRES_PASSWORD=postgres_password
    healthcheck:
      #CHANGE 1: this command checks if the database is ready, right on the source db server
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    container_name: postgres
    volumes:
      - ./loanDataService-Postgres/init/:/docker-entrypoint-initdb.d/
  
  loandata:
    build:
      context: ./loanDataService-Postgres
    environment:
      - PGHOST=postgres
      - PGUSER=postgres
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://172.17.0.1:4318"
    ports:
      - "3000:80"
    container_name: loandata
    depends_on:
      - postgres

  loanverification:
    build:
      context: ./loanVerificationService
    environment:
      - LOANDATA_SERVICE=loandata
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://172.17.0.1:4318"
    container_name: loanverification
    depends_on:
      - loandata

  loanapproval:
    build:
      context: ./loanApprovalService
    environment:
      - LOANDATA_SERVICE=loandata
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://172.17.0.1:4318"
    container_name: loanapproval
    depends_on:
      - loandata

  loanprocessor:
    build:
      context: ./loanProcessorService
    container_name: loanprocessor
    ports:
      - "3006:80"
    environment:
      - LOANDATA_SERVICE=loandata
      - LOANVERIFICATION_SERVICE=loanverification
      - LOANAPPROVAL_SERVICE=loanapproval
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://172.17.0.1:4318"
    depends_on:
      - loandata
      - loanverification
      - loanapproval

# special case, environment varirables are forced through entrypoint to set proxy on start
# otherwise, they do not get set
# startup.sh will ultimately run npm after things are set correctly
  loanui:
    build:
      context: ./loanUI
    container_name: loanui
    ports:
      - "8003:3000"
    depends_on:
      - loanprocessor
    entrypoint: ["./startup.sh", "loandata", "loanprocessor"]
    

